// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_render.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/List.tsx";
import * as $$1 from "./islands/Module.tsx";

const manifest = {
  routes: {
    "./routes/pkg/[name].tsx": $0,
    "./routes/_render.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/List.tsx": $$0,
    "./islands/Module.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
